version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
    - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile   
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

To run the application, use the following command:
    # docker-compose up --build

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

    # To run the database, use the following command:
    # docker-compose up db  

    # To run the entire application stack, use:
    # docker-compose up


